[package]
name = "octree"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {version = "0.16.1", features = ["dynamic_linking"]}
bevy_flycam = "0.16.1"
noise = "0.9.0"
num-traits = "0.2.19"
rayon = "1.10.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

